apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupons-svc
  namespace: checkout
  labels:
    app: coupons-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupons-svc
  template:
    metadata:
      labels:
        app: coupons-svc
    spec:
      containers:
        - name: app
          image: stefanprodan/podinfo:6.5.3
          ports:
            - name: http
              containerPort: 9898
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: coupons-svc
  namespace: checkout
  labels:
    app: coupons-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9898
      targetPort: http
  selector:
    app: coupons-svc
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coupons-svc
  namespace: checkout
  labels:
    app: coupons-svc
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: coupons-svc
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
