---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.slok.io
  resources:
  - servicelevelobjectives
  - slocorrelations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.slok.io
  resources:
  - servicelevelobjectives/finalizers
  verbs:
  - update
- apiGroups:
  - observability.slok.io
  resources:
  - servicelevelobjectives/status
  - slocorrelations/status
  verbs:
  - get
  - patch
  - update
