apiVersion: observability.slok.io/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    app.kubernetes.io/name: slok
    app.kubernetes.io/managed-by: kustomize
  name: example-app-availability
spec:
  displayName: "Example App Availability"
  objective:
    name: availability
    target: 99.9
    window: 30d
    sli:
      template:
        name: http-availability
        labels:
          service: "example-app"
