apiVersion: observability.slok.io/v1alpha1
kind: SLOComposition
metadata:
  labels:
    app.kubernetes.io/name: slok
    app.kubernetes.io/managed-by: kustomize
  name: example-app-slo-composition
spec:
  target: 99.9
  window: 30d
  objectives:
    - name: example-app-availability    # alias
      ref:
        name: example-app-availability  # ServiceLevelObjective resource name
    - name: example-app-latency         # alias
      ref:
        name: example-app-latency       # ServiceLevelObjective resource name
  composition:
    type: AND_MIN
