apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "slok.fullname" . }}-manager-role
  labels:
    {{- include "slok.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observability.slok.io
  resources:
  - servicelevelobjectives
  - slocompositions
  - slocorrelations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - observability.slok.io
  resources:
  - servicelevelobjectives/finalizers
  - slocompositions/finalizers
  verbs:
  - update
- apiGroups:
  - observability.slok.io
  resources:
  - servicelevelobjectives/status
  - slocompositions/status
  - slocorrelations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
