{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slok.metricsServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slok.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: {{ .Values.metrics.port }}
  selector:
    {{- include "slok.selectorLabels" . | nindent 4 }}
{{- end }}
