{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "slok.fullname" . }}-slo-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slok.labels" . | nindent 4 }}
    release: prometheus
spec:
  groups:
  - name: slok.slo
    rules:
    {{- if .Values.prometheusRule.rules.sloAtRisk.enabled }}
    - alert: SLOObjectiveAtRisk
      expr: |
        optimization_request_objective_status{
          status=~"at-risk"
        } == 1
      for: {{ .Values.prometheusRule.rules.sloAtRisk.for }}
      labels:
        severity: {{ .Values.prometheusRule.rules.sloAtRisk.severity }}
      annotations:
        summary: "SLO objective at risk"
        description: >
          ServiceLevelObjective {{ "{{" }} $labels.service_level_objective {{ "}}" }}
          in namespace {{ "{{" }} $labels.namespace {{ "}}" }}
          has objective {{ "{{" }} $labels.objective_name {{ "}}" }}
          at risk for more than {{ .Values.prometheusRule.rules.sloAtRisk.for }}.
    {{- end }}
    {{- if .Values.prometheusRule.rules.sloViolated.enabled }}
    - alert: SLOObjectiveViolated
      expr: |
        optimization_request_objective_status{
          status=~"violated"
        } == 1
      for: {{ .Values.prometheusRule.rules.sloViolated.for }}
      labels:
        severity: {{ .Values.prometheusRule.rules.sloViolated.severity }}
      annotations:
        summary: "SLO objective violated"
        description: >
          ServiceLevelObjective {{ "{{" }} $labels.service_level_objective {{ "}}" }}
          in namespace {{ "{{" }} $labels.namespace {{ "}}" }}
          has objective {{ "{{" }} $labels.objective_name {{ "}}" }}
          violated for more than {{ .Values.prometheusRule.rules.sloViolated.for }}.
    {{- end }}
{{- end }}
