apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: checkout

resources:
  - base/workload.yaml
  - base/slo.yaml
  - base/traffic-generator.yaml
  - payments/workload.yaml
  - payments/slo.yaml
  - payments/traffic-generator.yaml
  - coupons/workload.yaml
  - coupons/slo.yaml
  - coupons/traffic-generator.yaml
  - composition.yaml
