replicaCount: 1

image:
  repository: quay.io/flepera_kiratech/slok
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

leaderElection:
  enabled: true

webhook:
  enabled: true
  port: 9443
  failurePolicy: Fail

certManager:
  enabled: true
  issuer:
    create: true
    name: ""

metrics:
  enabled: true
  port: 8443

prometheus:
  url: "http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090"

healthProbe:
  port: 8081

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
